version: "3.7"

services:
    webapp:
        build: .
        container_name: influxnews
        volumes:
            - ./influxnews:/usr/src/influxnews
        env_file: .env
        ports:
            - 8000:8000