# Generated by Django 4.1.5 on 2023-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(default='')),
            ],
        ),
    ]
