# Generated by Django 4.1.5 on 2023-03-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
    ]
