# Generated by Django 4.1.5 on 2023-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0005_news_saved_by_news_view_count_news_viewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=9000),
        ),
    ]
